### ISSUE TITLE
Group Project

### ISSUE THREAD

**Issue by kevinho6** [Antonio-Kevin-Arnold/FoodRun#1]
My app is complete, please review. /cc @codepathreview

**Comment by minhchau273** [comment]
Hi there,

How are you going with your project? Could you create me GIF file to show your progress?

**Comment by kevinho6** [comment]
Hi Chau,

I just posted the GIF.

Thanks,
Kevin

**Comment by minhchau273** [comment]
:+1: Great job getting all the required stories done! This is a big milestone as now it's all about adding optionals and additional polish to the app.

Try to challenge yourself on the UI/visual side of things in the coming days. Not necessarily flashy things, but it's the small details that take a lot of work.
